//! Text PCK file writer for round-trip support.
//!
//! Reconstructs text PCK files from PCKSource, preserving text blocks and variable names.

use crate::prelude::*;
use crate::text_pck::{KernelValue, PCKBlock, PCKSource, PCKVariable};
use std::io::Write;
use std::path::Path;

/// Write a PCKSource to a text PCK file, preserving block structure.
pub fn write_text_pck(path: &Path, source: &PCKSource) -> Result<()> {
    let mut file = File::create(path)?;

    for block in &source.blocks {
        match block {
            PCKBlock::Text(text) => {
                // Write text block content as-is
                writeln!(file, "{}", text)?;
            }
            PCKBlock::Data(vars) => {
                // Write data block with delimiters
                writeln!(file, "\\begindata")?;
                writeln!(file)?;

                for var in vars {
                    write_variable(&mut file, var)?;
                }

                writeln!(file)?;
                writeln!(file, "\\begintext")?;
            }
        }
    }

    Ok(())
}

/// Write multiple PCK sources to a single text PCK file.
/// Sources are written sequentially with their block structure preserved.
pub fn write_text_pck_multi(path: &Path, sources: &[PCKSource]) -> Result<()> {
    if sources.is_empty() {
        return Err(Error::EmptyData { context: "No PCK sources to write".into() });
    }

    // If only one source, use simple write
    if sources.len() == 1 {
        return write_text_pck(path, &sources[0]);
    }

    let mut file = File::create(path)?;

    // Write header for combined file
    writeln!(file, "KPL/PCK")?;
    writeln!(file)?;
    writeln!(file, "Combined Planetary Constants Kernel")?;
    writeln!(file, "Generated by despice/respice")?;
    writeln!(file)?;

    // Write all sources, extracting just the data blocks
    for source in sources {
        for block in &source.blocks {
            if let PCKBlock::Data(vars) = block {
                writeln!(file, "\\begindata")?;
                writeln!(file)?;

                for var in vars {
                    write_variable(&mut file, var)?;
                }

                writeln!(file)?;
                writeln!(file, "\\begintext")?;
                writeln!(file)?;
            }
        }
    }

    Ok(())
}

/// Write a single PCK variable to a file.
fn write_variable<W: Write>(writer: &mut W, var: &PCKVariable) -> Result<()> {
    if var.values.is_empty() {
        return Ok(());
    }

    write!(writer, "        {} = ( ", var.name)?;

    // Write values with appropriate formatting
    let last_idx = var.values.len() - 1;
    for (i, value) in var.values.iter().enumerate() {
        // Format value based on type
        let formatted = format_kernel_value(value);
        write!(writer, "{}", formatted)?;

        if i < last_idx {
            write!(writer, " ")?;
        }
    }

    writeln!(writer, " )")?;

    Ok(())
}

/// Format a KernelValue for text kernel output.
fn format_kernel_value(value: &KernelValue) -> String {
    match value {
        KernelValue::Numeric(f) => format_numeric(*f),
        KernelValue::Epoch(s) => s.clone(), // Epoch strings already include @
        KernelValue::Text(s) => format!("'{}'", s), // Quote text values
    }
}

/// Format a floating point value for text kernel output.
fn format_numeric(value: f64) -> String {
    // Use scientific notation for very small values (before integer check)
    if value.abs() < 1e-6 && value != 0.0 {
        return format!("{:.6e}", value).replace('e', "D");
    }
    // Use scientific notation for very large values
    if value.abs() > 1e10 {
        return format!("{:.6e}", value).replace('e', "D");
    }
    // Check if it's effectively an integer
    if value.abs() < 1e12 && (value - value.round()).abs() < 1e-10 {
        return format!("{:.1}", value);
    }
    // Normal formatting with up to 10 decimal places
    let s = format!("{:.10}", value);
    // Trim trailing zeros after decimal point
    let s = s.trim_end_matches('0');
    if s.ends_with('.') {
        format!("{}0", s)
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_value_integer() {
        assert_eq!(format_numeric(286.0), "286.0");
        assert_eq!(format_numeric(0.0), "0.0");
        assert_eq!(format_numeric(-63.87), "-63.87");
    }

    #[test]
    fn test_format_value_decimal() {
        assert_eq!(format_numeric(360.9856235), "360.9856235");
    }

    #[test]
    fn test_format_value_scientific_small() {
        let v = format_numeric(1.4e-12);
        assert!(v.contains("D") || v.contains("e"));
    }
}
